export const FETCH_JOBS_REQUEST = "FETCH_JOBS_REQUEST";
export const FETCH_JOBS_SUCCESS = "FETCH_JOBS_SUCCESS";
export const FETCH_JOBS_FAILURE = "FETCH_JOBS_FAILURE";

export const CREATE_JOB_REQUEST = "CREATE_JOB_REQUEST";
export const CREATE_JOB_SUCCESS = "CREATE_JOB_SUCCESS";
export const CREATE_JOB_FAILURE = "CREATE_JOB_FAILURE";

export const FETCH_ALLJOBS_REQUEST = "FETCH_ALLJOBS_REQUEST";
export const FETCH_ALLJOBS_SUCCESS = "FETCH_ALLJOBS_SUCCESS";
export const FETCH_ALLJOBS_FAILURE = "FETCH_ALLJOBS_FAILURE";

export const SAVE_JOB_REQUEST = "SAVE_JOB_REQUEST";
export const SAVE_JOB_SUCCESS = "SAVE_JOB_SUCCESS";
export const SAVE_JOB_FAILURE = "SAVE_JOB_FAILURE";

export const UNSAVE_JOB_REQUEST = "UNSAVE_JOB_REQUEST";
export const UNSAVE_JOB_SUCCESS = "UNSAVE_JOB_SUCCESS";
export const UNSAVE_JOB_FAILURE = "UNSAVE_JOB_FAILURE";

export const FETCH_SAVE_JOBS_REQUEST = "FETCH_SAVE_JOBS_REQUEST";
export const FETCH_SAVE_JOBS_SUCCESS = "FETCH_SAVE_JOBS_SUCCESS";
export const FETCH_SAVE_JOBS_FAILURE = "FETCH_SAVE_JOBS_FAILURE";

export const FETCH_MY_RESUMES_REQUEST = "FETCH_MY_RESUMES_REQUEST";
export const FETCH_MY_RESUMES_SUCCESS = "FETCH_MY_RESUMES_SUCCESS";
export const FETCH_MY_RESUMES_FAILURE = "FETCH_MY_RESUMES_FAILURE";

export const UPLOAD_RESUME_REQUEST = "UPLOAD_RESUME_REQUEST";
export const UPLOAD_RESUME_SUCCESS = "UPLOAD_RESUME_SUCCESS";
export const UPLOAD_RESUME_FAILURE = "UPLOAD_RESUME_FAILURE";

export const APPLY_JOB_REQUEST = "APPLY_JOB_REQUEST";
export const APPLY_JOB_SUCCESS = "APPLY_JOB_SUCCESS";
export const APPLY_JOB_FAILURE = "APPLY_JOB_FAILURE";

export const PUBLISH_JOB_REQUEST = "PUBLISH_JOB_REQUEST";
export const PUBLISH_JOB_SUCCESS = "PUBLISH_JOB_SUCCESS";
export const PUBLISH_JOB_FAILURE = "PUBLISH_JOB_FAILURE";
